apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-serving
  labels:
    app: tensorflow-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow-serving
  template:
    metadata:
      labels:
        app: tensorflow-serving
    spec:
      containers:
      - name: tensorflow-serving
        image: tf_batch10_10x10:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: tensorflow-serving-svc
spec:
  selector:
    app: tensorflow-serving
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501